[package]
name = "snowstorm"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
csv = "1.3.0"
dotenv = "0.15.0"
eyre = "0.6.9"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
perfect_rand = "0.1.5"
rand = "0.8.5"
simd-json = "0.13.4"
sqlx = { version = "0.7.3", features = ["postgres", "runtime-tokio"] }
tokio = { version = "1.34.0", features = ["full"] }
uuid = "1.6.1"
